version: '2'

services:
  api_adidas:
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      # Mounts the project directory on the host to /app inside the container,
      - ./server:/app
      - /app/node_modules/
    # Expose ports [HOST:CONTAINER}
    ports:
      - "4040:4040"
    # Set environment variables from this file
    env_file:
      - ./server/.env
    # Link to containers in another service.
    container_name: "api_adidas"
    links:
      - mongo_adidas
  mongo_adidas:
    image: "mongo:3.4"
    ports:
      - "27017:27017"
    container_name: "adidas_mongodb"
  client_adidas:
    build:
      context: client
      dockerfile: Dockerfile
    volumes:
      # Mounts the project directory on the host to /app inside the container,
      - ./client:/app
      - /app/node_modules/
    # Expose ports [HOST:CONTAINER}
    ports:
      - "3000:3000"
    container_name: "client_adidas"

